name: apps_al_haddad
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  qr_flutter: ^4.0.0
  package_info_plus: ^1.4.2
  flutter_pos_printer_platform: ^1.0.9
  image_picker: ^0.8.6
  esc_pos_utils: ^1.1.0
  esc_pos_printer: ^4.1.0
  pull_to_refresh: ^2.0.0
  haversine_distance: ^1.2.1
  modal_bottom_sheet: ^2.1.0
  scan: ^1.6.0
  mobile_scanner: ^2.0.0
  scroll_navigation: ^1.3.2
  fl_chart: ^0.20.1
  flutter_inappwebview: 5.4.1+1
  flutter_barcode_scanner: ^2.0.0
  syncfusion_flutter_charts: 20.1.55
  animated_splash_screen: ^1.1.0
  carousel_slider: ^4.0.0
  dio: ^4.0.0
  eva_icons_flutter: ^3.0.2
  flutter_custom_clippers: ^2.0.0
  flutter_easyloading: ^3.0.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^1.0.4
  flutter_slidable: ^2.0.0
  get_storage: ^2.0.3
  http: ^0.13.3
  intl: ^0.17.0
  json_annotation: ^4.0.1
  path: ^1.8.0
  provider: ^6.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: 8.0.1
  shared_preferences:
  location: ^4.4.0
  url_launcher: ^6.0.18
  flutter_localizations:
    sdk: flutter
  firebase_messaging: ^11.4.0
  firebase_core: 1.17.1
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.15
  accordion: 2.4.0
  flutterfire_cli: 0.2.2+2
  flutter_local_notifications: 9.5.3+1
  fluttertoast: 8.0.9
  local_assets_server: ^2.0.2+10

dev_dependencies:
  build_runner: ^1.12.2
  json_serializable: any
#  flutter_test:
#    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/pos/index.html
    - assets/pos/
    - assets/pos/assets/
    - assets/pos/assets/css/
    - assets/pos/assets/css/vendors/
    - assets/pos/assets/css/vendors/font-awesome/
    - assets/pos/assets/css/vendors/google-fonts/
    - assets/pos/assets/css/vendors/webfonts/
    - assets/pos/assets/fonts/
    - assets/pos/assets/fonts/material-icon/
    - assets/pos/assets/fonts/material-icon/css/
    - assets/pos/assets/imgs/
    - assets/pos/assets/imgs/brands/
    - assets/pos/assets/imgs/card-brands/
    - assets/pos/assets/imgs/icons/
    - assets/pos/assets/imgs/items/
    - assets/pos/assets/imgs/misc/
    - assets/pos/assets/imgs/people/
    - assets/pos/assets/imgs/theme/
    - assets/pos/assets/js/
    - assets/pos/assets/js/vendors/
    - assets/pos/assets/js/vendors/font-awesome/
    - assets/pos/assets/js/vendors/sweetalert2/
    - assets/pos/assets/sass/
    - assets/pos/assets/sass/abstracts/
    - assets/pos/assets/sass/base/
    - assets/pos/assets/sass/components/
    - assets/pos/assets/sass/layout/
  # - assets/dummy/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          style: normal
          weight: 800

flutter_icons:
  ios: true
  android: true
  image_path: 'assets/icons/icon_alhaddad.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/icons/icon_alhaddad.png'
flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false
